# This file checks that the lib runs on ARM
on:
    push:
        branches: 'master'
        tags: '' # Restrict to blank tags
    pull_request:

jobs:
 dockerpi:
    name: Raspbian Buster pi Docker
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
        clean: false
    - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - run: docker run -i -v "${PWD}/..:${PWD}/.." lebarsfa/pi:buster-for-codac /bin/bash -c "uname -a && cat /etc/os-release && cd ${PWD} && pwd && lsb_release -a && sudo apt-get -q update --allow-releaseinfo-change ; sudo apt-get -y install libeigen3-dev ; wget https://github.com/lebarsfa/ibex-lib/releases/download/ibex-2.8.9.20220812/ibex_armv6hf_buster.zip --no-check-certificate -nv ; unzip -q ibex_armv6hf_buster.zip && rm -Rf ibex_armv6hf_buster.zip && sudo cp -Rf ibex/* /usr/local/ && mkdir build ; cd build && cmake -E env CXXFLAGS="-fPIC" CFLAGS="-fPIC" cmake -D CMAKE_INSTALL_PREFIX=../codac .. && cmake --build . --target install && cd .. && mkdir -p codac_standalone/example ; cd codac_standalone ; wget https://community.chocolatey.org/api/v2/package/eigen/3.4.0 --no-check-certificate -nv ; unzip -q 3.4.0 -d eigen ; rm -Rf 3.4.0 eigen/*.xml eigen/*.nuspec eigen/_* eigen/package eigen/tools ; mkdir -p ibex/include ; mkdir -p ibex/lib ; mkdir -p ibex/share ; mkdir -p ibex/bin ; cp -Rf /usr/local/include/ibex* ibex/include/ ; cp -Rf /usr/local/lib/*ibex* ibex/lib/ ; cp -Rf /usr/local/share/*ibex* ibex/share/ ; cp -Rf /usr/local/share/pkgconfig ibex/share/ ; cp -Rf /usr/local/bin/ibex* ibex/bin/ ; cp -Rf ../codac . ; cp -Rf ../tests/test_codac/* ./example/ ; cd .. ; zip -q -r codac_standalone_armv6hf_buster.zip codac_standalone ; cd codac_standalone/example && cmake . && cmake --build . && ./my_project"
    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.zip"
        overwrite: true
        tag_name: autotagname-${{ github.sha }}
      if: (github.event_name != 'pull_request')&&(github.ref_name == 'master')
